version: "3.7"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  web:
    build: .
    container_name: expense-tracker
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      JWT_SECRET_KEY: "supersecretkey"

volumes:
  mongo-data:
